context:
  version: "0.2.4"

package:
  name: analogjs-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@analogjs/language-server/-/language-server-${{ version }}.tgz
  sha256: d27f1e3f087c39ac0e947ec47cee7bc80196fc2eda90c03fea668378d9bd4099

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "analog-language-server 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: LSP server for AnalogJS Language Service
  homepage: https://analogjs.org/
  repository: https://github.com/analogjs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
