context:
  version: "0.1.7"

package:
  name: analogjs-language-server
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@analogjs/language-server/-/language-server-${{ version }}.tgz
  sha256: 2d9fac241de9865dccb64023b99c3f1c519a047d4cb50ec675a15c8fca1af45f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "analog-language-server 2>&1 | grep -q \"Connection input stream is not set.\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: LSP server for AnalogJS Language Service
  homepage: https://analogjs.org/
  repository: https://github.com/analogjs/language-tools

extra:
  recipe-maintainers:
    - danielnachun
